(setq user-emacs-directory "~/.emacs.d.shell")
(add-to-list 'load-path "~/.emacs.d.shell/lisp")
;; (require 'init-funcs)
(require 'init-packages)
(require 'init-ui)
(require 'init-better-defaults)
(require 'init-org)
(require 'init-keybindings)
(setq custom-file (expand-file-name "lisp/custom.el" user-emacs-directory))
;; (load-file custom-file)
